name = "MyProjecct"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["MyProjecct"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#v4.23.0"

[[lean_lib]]
name = "MyProjecct"
